name: 'Test Report'
permissions: read-all

on:
  workflow_run:
    workflows: [ build ]
    types: [ completed ]
    branches: [ master, v2.dev, v3.dev ]

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: test-results
    - name: Truncate test results
      run: find . -type f -name '*.xml' -exec sh -c 'grep testsuite {} > {}.out && mv {}.out {}' \;
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        comment_mode: off
        files: '**/*.xml'
        check_run_annotations: none
    - name: Publish Unit Test Results (phoenix-actions)
      uses: phoenix-actions/test-reporting@v3
      continue-on-error: true
      id: test-report
      with:
        name: Tests
        path: '**/*.xml'
        reporter: java-junit
